# Generated by Django 2.0.2 on 2018-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=False)),
                ('product_name', models.CharField(default=False, max_length=25)),
                ('quantity', models.IntegerField(default=False)),
                ('price', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.CharField(default=False, max_length=15)),
                ('total_amt', models.IntegerField(default=False)),
                ('ordered_items', models.CharField(default=False, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.CharField(default=False, max_length=15)),
                ('total_amt', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(default=False, max_length=15)),
                ('category', models.CharField(default=False, max_length=15)),
                ('product_name', models.CharField(default=False, max_length=30)),
                ('availability', models.CharField(default=False, max_length=10)),
                ('price', models.IntegerField(default=False)),
                ('link', models.CharField(default=False, max_length=1000)),
                ('quantity', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(default=False, max_length=15)),
                ('quantity_available', models.CharField(default=False, max_length=10)),
                ('item_name', models.CharField(default=False, max_length=25)),
            ],
        ),
    ]
